import type { Product, Category } from './types'

const img = (id: number, slug: string) =>
  `https://cocorikush.fr/${id}-large_default/${slug}.jpg`

export const CATEGORIES: { slug: Category; label: string; emoji: string }[] = [
  { slug: 'fleur-cbd', label: 'Fleurs CBD', emoji: '🌿' },
  { slug: 'fleur-californienne', label: 'Fleurs Californiennes', emoji: '🌴' },
  { slug: 'resine-cbd', label: 'Résines CBD', emoji: '🧱' },
  { slug: 'hec-10', label: 'HEC-10', emoji: '⚡' },
  { slug: '10-oh-hhc', label: '10-OH-HHC', emoji: '🔬' },
  { slug: 'thca', label: 'THCA', emoji: '💎' },
  { slug: 'magic-sauce', label: 'Magic Sauce', emoji: '🧪' },
  { slug: 'cbn', label: 'CBN', emoji: '🌙' },
  { slug: 'puff-vape', label: 'Puffs & Vapes', emoji: '💨' },
  { slug: 'delta-9', label: 'Delta-9', emoji: '🍬' },
  { slug: 'cookies', label: 'Cookies', emoji: '🍪' },
  { slug: 'accessoires', label: 'Accessoires', emoji: '🛠️' },
]

export const PROMOS = {
  WELCOME10: { code: 'WELCOME10', discount: 10, minOrder: 30 },
  CANNAZEN20: { code: 'CANNAZEN20', discount: 20, minOrder: 80 },
  FLASH15: { code: 'FLASH15', discount: 15, minOrder: 50 },
}

export const PRODUCTS: Product[] = [
  // ═══════════════════════════════════════
  // FLEURS CBD
  // ═══════════════════════════════════════
  {
    id: '3412',
    slug: 'blueberry-muffin',
    name: 'Blueberry Muffin',
    category: 'fleur-cbd',
    legalStatus: 'legal',
    legalNote: 'CBD < 0.3% THC — 100% légal en France',
    smokellierQuote: 'Un muffin aux myrtilles tout droit sorti du four. Doux, fruité, réconfortant.',
    tasteScore: 9.2,
    effectScore: 7.5,
    description: 'La Blueberry Muffin est une fleur CBD indoor aux arômes intenses de myrtille et de pâtisserie. Sa structure dense et résineuse libère des notes sucrées et fruitées incomparables. Un classique pour les amateurs de saveurs gourmandes.',
    aromas: ['Myrtille', 'Pâtisserie', 'Sucré', 'Fruité'],
    effects: ['Relaxation', 'Bien-être', 'Anti-stress'],
    variants: [
      { label: '3g', pricePerUnit: 4.33, totalPrice: 12.99, inStock: true },
      { label: '5g', pricePerUnit: 3.80, totalPrice: 18.99, discount: 12, inStock: true },
      { label: '10g', pricePerUnit: 3.30, totalPrice: 32.99, discount: 24, inStock: true },
      { label: '25g', pricePerUnit: 2.80, totalPrice: 69.99, discount: 35, inStock: true },
      { label: '50g', pricePerUnit: 2.40, totalPrice: 119.99, discount: 45, inStock: true },
    ],
    images: [img(3412, 'blueberry-muffin')],
    isNew: false,
    isBestSeller: true,
    isOnSale: false,
    stock: 150,
  },
  {
    id: '3380',
    slug: 'gorilla-glue',
    name: 'Gorilla Glue',
    category: 'fleur-cbd',
    legalStatus: 'legal',
    legalNote: 'CBD < 0.3% THC — 100% légal en France',
    smokellierQuote: 'Puissante, terreuse, collante. La Gorilla ne lâche rien.',
    tasteScore: 8.8,
    effectScore: 8.5,
    description: 'La Gorilla Glue CBD est une légende. Ses trichomes ultra-collants et son profil terpénique terreux et boisé en font une référence. Cultivée en indoor pour une qualité irréprochable.',
    aromas: ['Terreux', 'Pin', 'Diesel', 'Boisé'],
    effects: ['Relaxation profonde', 'Détente musculaire', 'Calme'],
    variants: [
      { label: '3g', pricePerUnit: 4.33, totalPrice: 12.99, inStock: true },
      { label: '5g', pricePerUnit: 3.80, totalPrice: 18.99, discount: 12, inStock: true },
      { label: '10g', pricePerUnit: 3.30, totalPrice: 32.99, discount: 24, inStock: true },
      { label: '25g', pricePerUnit: 2.80, totalPrice: 69.99, discount: 35, inStock: true },
    ],
    images: [img(3380, 'gorilla-glue')],
    isNew: false,
    isBestSeller: true,
    isOnSale: false,
    stock: 120,
  },
  {
    id: '3424',
    slug: 'amnesia',
    name: 'Amnesia',
    category: 'fleur-cbd',
    legalStatus: 'legal',
    legalNote: 'CBD < 0.3% THC — 100% légal en France',
    smokellierQuote: 'Citronnée, vive, énergisante. L\'Amnesia CBD qui réveille les sens.',
    tasteScore: 8.5,
    effectScore: 7.8,
    description: 'L\'Amnesia CBD est une sativa dominante aux arômes citronnés et épicés. Sa saveur vive et son effet énergisant en font un choix parfait pour la journée. Cultivée en indoor avec soin.',
    aromas: ['Citron', 'Haze', 'Épicé', 'Agrumes'],
    effects: ['Énergie', 'Focus', 'Bonne humeur'],
    variants: [
      { label: '3g', pricePerUnit: 3.99, totalPrice: 11.99, inStock: true },
      { label: '5g', pricePerUnit: 3.60, totalPrice: 17.99, discount: 10, inStock: true },
      { label: '10g', pricePerUnit: 3.00, totalPrice: 29.99, discount: 25, inStock: true },
      { label: '25g', pricePerUnit: 2.60, totalPrice: 64.99, discount: 35, inStock: true },
    ],
    images: [img(3424, 'amnesia')],
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 90,
  },
  {
    id: '3376',
    slug: 'fat-banana',
    name: 'Fat Banana',
    category: 'fleur-cbd',
    legalStatus: 'legal',
    legalNote: 'CBD < 0.3% THC — 100% légal en France',
    smokellierQuote: 'Banane mûre, crémeuse, tropicale. Un dessert en fleur.',
    tasteScore: 9.0,
    effectScore: 7.2,
    description: 'La Fat Banana CBD offre des arômes de banane mûre et de vanille. Cette indica dominante est parfaite pour les moments de détente avec sa saveur crémeuse et réconfortante.',
    aromas: ['Banane', 'Vanille', 'Crémeux', 'Tropical'],
    effects: ['Relaxation', 'Détente', 'Sommeil'],
    variants: [
      { label: '3g', pricePerUnit: 4.33, totalPrice: 12.99, inStock: true },
      { label: '5g', pricePerUnit: 3.80, totalPrice: 18.99, discount: 12, inStock: true },
      { label: '10g', pricePerUnit: 3.30, totalPrice: 32.99, discount: 24, inStock: true },
      { label: '25g', pricePerUnit: 2.80, totalPrice: 69.99, discount: 35, inStock: true },
    ],
    images: [img(3376, 'fat-banana')],
    isNew: false,
    isBestSeller: true,
    isOnSale: false,
    stock: 100,
  },
  {
    id: '3226',
    slug: 'pop-corn',
    name: 'Pop Corn',
    category: 'fleur-cbd',
    legalStatus: 'legal',
    legalNote: 'CBD < 0.3% THC — 100% légal en France',
    smokellierQuote: 'Petites buds croquantes au goût sucré. Le snack du connaisseur.',
    tasteScore: 7.5,
    effectScore: 6.8,
    description: 'Les Pop Corn CBD sont de petites têtes compactes et résineuses, idéales pour un usage quotidien. Prix mini, qualité maxi. Un excellent rapport qualité-prix pour découvrir le CBD.',
    aromas: ['Sucré', 'Terreux', 'Herbal'],
    effects: ['Léger', 'Bien-être', 'Quotidien'],
    variants: [
      { label: '5g', pricePerUnit: 2.00, totalPrice: 9.99, inStock: true },
      { label: '10g', pricePerUnit: 1.80, totalPrice: 17.99, discount: 10, inStock: true },
      { label: '25g', pricePerUnit: 1.60, totalPrice: 39.99, discount: 20, inStock: true },
      { label: '50g', pricePerUnit: 1.40, totalPrice: 69.99, discount: 30, inStock: true },
    ],
    images: [img(3226, 'pop-corn')],
    isNew: false,
    isBestSeller: false,
    isOnSale: true,
    discountPct: 20,
    stock: 200,
  },
  {
    id: '3385',
    slug: 'purple-haze',
    name: 'Purple Haze',
    category: 'fleur-cbd',
    legalStatus: 'legal',
    legalNote: 'CBD < 0.3% THC — 100% légal en France',
    smokellierQuote: 'Violette, fruitée, mystique. Hendrix approuverait.',
    tasteScore: 8.7,
    effectScore: 7.6,
    description: 'La Purple Haze CBD arbore de magnifiques teintes violettes et des arômes de fruits rouges et d\'épices. Une fleur emblématique revisitée en version CBD, cultivée en indoor.',
    aromas: ['Fruits rouges', 'Épicé', 'Floral', 'Baies'],
    effects: ['Créativité', 'Bonne humeur', 'Énergie douce'],
    variants: [
      { label: '3g', pricePerUnit: 4.33, totalPrice: 12.99, inStock: true },
      { label: '5g', pricePerUnit: 3.80, totalPrice: 18.99, discount: 12, inStock: true },
      { label: '10g', pricePerUnit: 3.30, totalPrice: 32.99, discount: 24, inStock: true },
    ],
    images: [img(3385, 'purple-haze')],
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 80,
  },
  {
    id: '3448',
    slug: 'strawberry',
    name: 'Strawberry',
    category: 'fleur-cbd',
    legalStatus: 'legal',
    legalNote: 'CBD < 0.3% THC — 100% légal en France',
    smokellierQuote: 'Fraise des bois, sucrée et délicate. Un bijou CBD.',
    tasteScore: 9.1,
    effectScore: 7.0,
    description: 'La Strawberry CBD est une fleur aux arômes intenses de fraise et de bonbon. Sa douceur et sa légèreté en font une favorite des palais exigeants.',
    aromas: ['Fraise', 'Bonbon', 'Sucré', 'Fruité'],
    effects: ['Relaxation légère', 'Bonne humeur', 'Bien-être'],
    variants: [
      { label: '3g', pricePerUnit: 4.33, totalPrice: 12.99, inStock: false },
      { label: '5g', pricePerUnit: 3.80, totalPrice: 18.99, inStock: false },
      { label: '10g', pricePerUnit: 3.30, totalPrice: 32.99, inStock: false },
    ],
    images: [img(3448, 'strawberry')],
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 0,
    isOutOfStock: true,
  },
  {
    id: '3384',
    slug: 'mango-kush',
    name: 'Mango Kush',
    category: 'fleur-cbd',
    legalStatus: 'legal',
    legalNote: 'CBD < 0.3% THC — 100% légal en France',
    smokellierQuote: 'Mangue juteuse et kush profond. Le soleil dans un bud.',
    tasteScore: 8.9,
    effectScore: 7.4,
    description: 'La Mango Kush CBD combine des arômes tropicaux de mangue avec la profondeur d\'une Kush classique. Parfaitement équilibrée entre saveur et relaxation.',
    aromas: ['Mangue', 'Tropical', 'Kush', 'Sucré'],
    effects: ['Relaxation', 'Évasion', 'Bien-être'],
    variants: [
      { label: '3g', pricePerUnit: 4.33, totalPrice: 12.99, inStock: true },
      { label: '5g', pricePerUnit: 3.80, totalPrice: 18.99, discount: 12, inStock: true },
      { label: '10g', pricePerUnit: 3.30, totalPrice: 32.99, discount: 24, inStock: true },
      { label: '25g', pricePerUnit: 2.80, totalPrice: 69.99, discount: 35, inStock: true },
    ],
    images: [img(3384, 'mango-kush')],
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 95,
  },

  // ═══════════════════════════════════════
  // FLEURS CALIFORNIENNES
  // ═══════════════════════════════════════
  {
    id: '4200',
    slug: 'canette-fat-banana',
    name: 'Canette Fat Banana',
    category: 'fleur-californienne',
    legalStatus: 'grey-zone',
    legalNote: 'Molécule en zone grise — consommation à vos risques',
    warningNote: 'Produit puissant — non recommandé aux débutants',
    smokellierQuote: 'La Fat Banana version californienne. Puissance x10, saveur x100.',
    tasteScore: 9.5,
    effectScore: 9.2,
    description: 'La Canette Fat Banana est une version californienne ultra-premium de la classique Fat Banana. Conditionnée en canette scellée pour une fraîcheur maximale. Terpènes explosifs, puissance inégalée.',
    aromas: ['Banane intense', 'Vanille', 'Crème', 'Tropical'],
    effects: ['Puissant', 'Euphorie', 'Relaxation intense'],
    variants: [
      { label: '3.5g', pricePerUnit: 8.57, totalPrice: 29.99, inStock: true },
    ],
    images: [img(4200, 'canette-fat-banana')],
    molecule: 'THC-P',
    moleculeColor: '#f59e0b',
    isNew: true,
    isBestSeller: false,
    isOnSale: false,
    stock: 40,
    isHigh: true,
  },
  {
    id: '4625',
    slug: 'trump-skunk',
    name: 'Trump Skunk',
    category: 'fleur-californienne',
    legalStatus: 'grey-zone',
    legalNote: 'Molécule en zone grise — consommation à vos risques',
    warningNote: 'Produit puissant — non recommandé aux débutants',
    smokellierQuote: 'Skunk présidentielle. Make Cannabis Great Again.',
    tasteScore: 8.8,
    effectScore: 9.0,
    description: 'La Trump Skunk est une fleur californienne au profil skunk intense et mémorable. Un nom provocateur pour une qualité qui ne fait pas de compromis.',
    aromas: ['Skunk', 'Terreux', 'Diesel', 'Piquant'],
    effects: ['Puissant', 'Créativité', 'Euphorie'],
    variants: [
      { label: '1g', pricePerUnit: 9.99, totalPrice: 9.99, inStock: true },
      { label: '3g', pricePerUnit: 8.33, totalPrice: 24.99, discount: 17, inStock: true },
      { label: '5g', pricePerUnit: 7.60, totalPrice: 37.99, discount: 24, inStock: true },
    ],
    images: [img(4625, 'trump-skunk')],
    molecule: 'THC-P',
    moleculeColor: '#f59e0b',
    isNew: true,
    isBestSeller: false,
    isOnSale: false,
    stock: 35,
    isHigh: true,
  },
  {
    id: '4640',
    slug: 'lady-banana',
    name: 'Lady Banana',
    category: 'fleur-californienne',
    legalStatus: 'grey-zone',
    legalNote: 'Molécule en zone grise — consommation à vos risques',
    warningNote: 'Produit puissant — non recommandé aux débutants',
    smokellierQuote: 'Élégante, sucrée, puissante. La diva des californiennes.',
    tasteScore: 9.3,
    effectScore: 9.1,
    description: 'Lady Banana est une fleur californienne premium aux notes de banane caramélisée. Texture parfaite, trichomes étincelants, effets puissants et durables.',
    aromas: ['Banane caramélisée', 'Sucré', 'Crème', 'Vanille'],
    effects: ['Euphorie', 'Relaxation', 'Créativité'],
    variants: [
      { label: '1g', pricePerUnit: 9.99, totalPrice: 9.99, inStock: true },
      { label: '3g', pricePerUnit: 8.33, totalPrice: 24.99, discount: 17, inStock: true },
      { label: '5g', pricePerUnit: 7.60, totalPrice: 37.99, discount: 24, inStock: true },
    ],
    images: [img(4640, 'lady-banana')],
    molecule: 'THC-P',
    moleculeColor: '#f59e0b',
    isNew: true,
    isBestSeller: true,
    isOnSale: false,
    stock: 30,
    isHigh: true,
  },
  {
    id: '4642',
    slug: 'elon-dream',
    name: 'Elon Dream',
    category: 'fleur-californienne',
    legalStatus: 'grey-zone',
    legalNote: 'Molécule en zone grise — consommation à vos risques',
    warningNote: 'Produit puissant — non recommandé aux débutants',
    smokellierQuote: 'Rêve spatial, terpènes d\'un autre monde. To the moon.',
    tasteScore: 9.0,
    effectScore: 9.4,
    description: 'L\'Elon Dream est une fleur californienne visionnaire. Arômes spatiaux, effets décollants. Une expérience hors du commun pour les connaisseurs avertis.',
    aromas: ['Agrumes', 'Pin', 'Haze', 'Épicé'],
    effects: ['Euphorie intense', 'Créativité', 'Énergie'],
    variants: [
      { label: '1g', pricePerUnit: 9.99, totalPrice: 9.99, inStock: true },
      { label: '3g', pricePerUnit: 8.33, totalPrice: 24.99, discount: 17, inStock: true },
      { label: '5g', pricePerUnit: 7.60, totalPrice: 37.99, discount: 24, inStock: true },
    ],
    images: [img(4642, 'elon-dream')],
    molecule: 'THC-P',
    moleculeColor: '#f59e0b',
    isNew: true,
    isBestSeller: false,
    isOnSale: false,
    stock: 28,
    isHigh: true,
  },
  {
    id: '4644',
    slug: 'merkel-cream',
    name: 'Merkel Cream',
    category: 'fleur-californienne',
    legalStatus: 'grey-zone',
    legalNote: 'Molécule en zone grise — consommation à vos risques',
    warningNote: 'Produit puissant — non recommandé aux débutants',
    smokellierQuote: 'Crème allemande. Rigueur et douceur en parfait équilibre.',
    tasteScore: 8.9,
    effectScore: 8.8,
    description: 'Merkel Cream est une fleur californienne crémeuse et raffinée. Son profil terpénique doux et lacté offre une expérience unique entre puissance et finesse.',
    aromas: ['Crème', 'Vanille', 'Biscuit', 'Lait'],
    effects: ['Relaxation profonde', 'Calme', 'Confort'],
    variants: [
      { label: '1g', pricePerUnit: 9.99, totalPrice: 9.99, inStock: true },
      { label: '3g', pricePerUnit: 8.33, totalPrice: 24.99, discount: 17, inStock: true },
      { label: '5g', pricePerUnit: 7.60, totalPrice: 37.99, discount: 24, inStock: true },
    ],
    images: [img(4644, 'merkel-cream')],
    molecule: 'THC-P',
    moleculeColor: '#f59e0b',
    isNew: true,
    isBestSeller: false,
    isOnSale: false,
    stock: 32,
    isHigh: true,
  },
  {
    id: '4646',
    slug: 'mobutu-hash',
    name: 'Mobutu Hash',
    category: 'fleur-californienne',
    legalStatus: 'grey-zone',
    legalNote: 'Molécule en zone grise — consommation à vos risques',
    warningNote: 'Produit puissant — non recommandé aux débutants',
    smokellierQuote: 'Hash royal, texture onctueuse. Le dictateur des saveurs.',
    tasteScore: 9.1,
    effectScore: 9.3,
    description: 'Le Mobutu Hash est une résine californienne pressée à la main. Texture fondante, arômes profonds de haschich traditionnel revisité avec une puissance moderne.',
    aromas: ['Hash traditionnel', 'Épicé', 'Boisé', 'Terreux'],
    effects: ['Puissant', 'Stone', 'Relaxation'],
    variants: [
      { label: '1g', pricePerUnit: 11.99, totalPrice: 11.99, inStock: true },
      { label: '3g', pricePerUnit: 9.99, totalPrice: 29.99, discount: 17, inStock: true },
      { label: '5g', pricePerUnit: 8.99, totalPrice: 44.99, discount: 25, inStock: true },
    ],
    images: [img(4646, 'mobutu-hash')],
    molecule: 'THC-P',
    moleculeColor: '#f59e0b',
    isNew: true,
    isBestSeller: false,
    isOnSale: false,
    stock: 25,
    isHigh: true,
  },

  // ═══════════════════════════════════════
  // RÉSINES CBD
  // ═══════════════════════════════════════
  {
    id: '3460',
    slug: 'ice-o-lator',
    name: 'Ice-O-Lator',
    category: 'resine-cbd',
    legalStatus: 'legal',
    legalNote: 'CBD < 0.3% THC — 100% légal en France',
    smokellierQuote: 'Pure, glacée, cristalline. L\'extraction à l\'eau dans toute sa splendeur.',
    tasteScore: 9.0,
    effectScore: 8.2,
    description: 'L\'Ice-O-Lator est une résine CBD extraite à l\'eau glacée. Cette méthode d\'extraction premium produit un concentré pur, riche en terpènes et en cannabinoïdes.',
    aromas: ['Frais', 'Pin', 'Herbal', 'Mentholé'],
    effects: ['Relaxation', 'Anti-douleur', 'Calme'],
    variants: [
      { label: '2g', pricePerUnit: 6.00, totalPrice: 11.99, inStock: true },
      { label: '5g', pricePerUnit: 5.00, totalPrice: 24.99, discount: 17, inStock: true },
      { label: '10g', pricePerUnit: 4.00, totalPrice: 39.99, discount: 33, inStock: true },
    ],
    images: [img(3460, 'ice-o-lator')],
    isNew: false,
    isBestSeller: true,
    isOnSale: false,
    stock: 70,
  },
  {
    id: '3240',
    slug: 'hash-afghan',
    name: 'Hash Afghan',
    category: 'resine-cbd',
    legalStatus: 'legal',
    legalNote: 'CBD < 0.3% THC — 100% légal en France',
    smokellierQuote: 'Le goût authentique de l\'Afghan. Tradition et savoir-faire.',
    tasteScore: 8.5,
    effectScore: 7.8,
    description: 'Le Hash Afghan CBD est une résine traditionnelle inspirée des méthodes de production afghanes. Texture malléable, arômes profonds et terreux. Un classique intemporel.',
    aromas: ['Terreux', 'Épicé', 'Boisé', 'Musc'],
    effects: ['Relaxation profonde', 'Sommeil', 'Anti-stress'],
    variants: [
      { label: '2g', pricePerUnit: 4.50, totalPrice: 8.99, inStock: true },
      { label: '5g', pricePerUnit: 4.00, totalPrice: 19.99, discount: 11, inStock: true },
      { label: '10g', pricePerUnit: 3.50, totalPrice: 34.99, discount: 22, inStock: true },
      { label: '25g', pricePerUnit: 3.00, totalPrice: 74.99, discount: 33, inStock: true },
    ],
    images: [img(3240, 'hash-afghan')],
    isNew: false,
    isBestSeller: false,
    isOnSale: true,
    discountPct: 15,
    stock: 110,
  },

  // ═══════════════════════════════════════
  // CBN
  // ═══════════════════════════════════════
  {
    id: '3580',
    slug: 'caramelo-cbn',
    name: 'Caramelo CBN',
    category: 'cbn',
    legalStatus: 'legal',
    legalNote: 'CBN légal en France — pas de THC',
    consumptionNote: 'Idéal en infusion ou vaporisation pour les effets sommeil',
    smokellierQuote: 'Caramel fondant et nuit profonde. Le CBN qui berce.',
    tasteScore: 8.8,
    effectScore: 8.5,
    description: 'Le Caramelo CBN est une résine enrichie en CBN (cannabinol), la molécule du sommeil. Arômes de caramel et de miel. Parfait pour les troubles du sommeil.',
    aromas: ['Caramel', 'Miel', 'Sucré', 'Vanille'],
    effects: ['Sommeil', 'Relaxation profonde', 'Anti-insomnie'],
    variants: [
      { label: '2g', pricePerUnit: 5.50, totalPrice: 10.99, inStock: true },
      { label: '5g', pricePerUnit: 4.80, totalPrice: 23.99, discount: 13, inStock: true },
      { label: '10g', pricePerUnit: 4.00, totalPrice: 39.99, discount: 27, inStock: true },
    ],
    images: [img(3580, 'caramelo-cbn')],
    molecule: 'CBN',
    moleculeColor: '#8b5cf6',
    isNew: false,
    isBestSeller: true,
    isOnSale: false,
    stock: 85,
  },
  {
    id: '3520',
    slug: 'escobar-cbn',
    name: 'Escobar CBN',
    category: 'cbn',
    legalStatus: 'legal',
    legalNote: 'CBN légal en France — pas de THC',
    consumptionNote: 'Idéal en infusion ou vaporisation',
    smokellierQuote: 'Le parrain du CBN. Puissant, sombre, inoubliable.',
    tasteScore: 8.5,
    effectScore: 8.8,
    description: 'L\'Escobar CBN est une résine CBN premium au profil sombre et intense. Arômes de café torréfié et de cacao. Pour ceux qui cherchent les effets CBN les plus prononcés.',
    aromas: ['Café', 'Cacao', 'Terreux', 'Fumé'],
    effects: ['Sommeil profond', 'Anti-douleur', 'Calme'],
    variants: [
      { label: '2g', pricePerUnit: 6.00, totalPrice: 11.99, inStock: true },
      { label: '5g', pricePerUnit: 5.00, totalPrice: 24.99, discount: 17, inStock: true },
      { label: '10g', pricePerUnit: 4.50, totalPrice: 44.99, discount: 25, inStock: true },
    ],
    images: [img(3520, 'escobar-cbn')],
    molecule: 'CBN',
    moleculeColor: '#8b5cf6',
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 60,
  },
  {
    id: '3522',
    slug: 'fleur-caramelo-cbn',
    name: 'Fleur Caramelo CBN',
    category: 'cbn',
    legalStatus: 'legal',
    legalNote: 'CBN légal en France — pas de THC',
    consumptionNote: 'Consommable en vaporisation ou infusion',
    smokellierQuote: 'La fleur Caramelo version CBN. Douce nuit garantie.',
    tasteScore: 9.0,
    effectScore: 8.3,
    description: 'La Fleur Caramelo CBN combine les arômes gourmands du caramelo avec les propriétés apaisantes du CBN. Une fleur premium pour des nuits paisibles.',
    aromas: ['Caramel', 'Floral', 'Doux', 'Miel'],
    effects: ['Sommeil', 'Relaxation', 'Sérénité'],
    variants: [
      { label: '3g', pricePerUnit: 5.00, totalPrice: 14.99, inStock: true },
      { label: '5g', pricePerUnit: 4.60, totalPrice: 22.99, discount: 8, inStock: true },
      { label: '10g', pricePerUnit: 4.00, totalPrice: 39.99, discount: 20, inStock: true },
    ],
    images: [img(3522, 'fleur-caramelo-cbn')],
    molecule: 'CBN',
    moleculeColor: '#8b5cf6',
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 55,
  },

  // ═══════════════════════════════════════
  // HEC-10
  // ═══════════════════════════════════════
  {
    id: '3600',
    slug: 'poutine-haze',
    name: 'Poutine Haze',
    category: 'hec-10',
    legalStatus: 'grey-zone',
    legalNote: 'HEC-10 — molécule en zone grise légale',
    warningNote: 'Effets psychoactifs possibles — commencer par de petites doses',
    smokellierQuote: 'Haze canadienne, effets dévastateurs. La poutine qui claque.',
    tasteScore: 8.5,
    effectScore: 9.0,
    description: 'La Poutine Haze HEC-10 est une fleur infusée avec de l\'hexahydrocannabinol. Profil haze classique avec une puissance augmentée. Pour les amateurs de sensations fortes.',
    aromas: ['Haze', 'Citron', 'Pin', 'Épicé'],
    effects: ['Psychoactif', 'Euphorie', 'Énergie'],
    variants: [
      { label: '1g', pricePerUnit: 8.99, totalPrice: 8.99, inStock: true },
      { label: '3g', pricePerUnit: 7.33, totalPrice: 21.99, discount: 18, inStock: true },
      { label: '5g', pricePerUnit: 6.60, totalPrice: 32.99, discount: 27, inStock: true },
    ],
    images: [img(3600, 'poutine-haze')],
    molecule: 'HEC-10',
    moleculeColor: '#06b6d4',
    isNew: false,
    isBestSeller: true,
    isOnSale: false,
    stock: 50,
    isHigh: true,
  },
  {
    id: '3598',
    slug: 'og-jinping',
    name: 'OG Jinping',
    category: 'hec-10',
    legalStatus: 'grey-zone',
    legalNote: 'HEC-10 — molécule en zone grise légale',
    warningNote: 'Effets psychoactifs possibles — commencer par de petites doses',
    smokellierQuote: 'OG impériale. Puissance et contrôle absolu.',
    tasteScore: 8.6,
    effectScore: 9.2,
    description: 'L\'OG Jinping est une fleur HEC-10 au profil OG classique. Diesel, terreux et puissant. Un produit qui impose le respect par sa qualité et son intensité.',
    aromas: ['Diesel', 'Terreux', 'Pin', 'Kush'],
    effects: ['Puissant', 'Stone', 'Relaxation intense'],
    variants: [
      { label: '1g', pricePerUnit: 8.99, totalPrice: 8.99, inStock: true },
      { label: '3g', pricePerUnit: 7.33, totalPrice: 21.99, discount: 18, inStock: true },
      { label: '5g', pricePerUnit: 6.60, totalPrice: 32.99, discount: 27, inStock: true },
    ],
    images: [img(3598, 'og-jinping')],
    molecule: 'HEC-10',
    moleculeColor: '#06b6d4',
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 45,
    isHigh: true,
  },
  {
    id: '3930',
    slug: 'yakuza-sour',
    name: 'Yakuza Sour',
    category: 'hec-10',
    legalStatus: 'grey-zone',
    legalNote: 'HEC-10 — molécule en zone grise légale',
    warningNote: 'Effets psychoactifs possibles — commencer par de petites doses',
    smokellierQuote: 'Acide, tranchante, impitoyable. La voie du guerrier.',
    tasteScore: 8.7,
    effectScore: 9.1,
    description: 'La Yakuza Sour est une fleur HEC-10 au profil sour diesel intense. Notes acides et piquantes, effets rapides et puissants. Pour les connaisseurs avertis.',
    aromas: ['Sour', 'Diesel', 'Citron', 'Acide'],
    effects: ['Euphorie', 'Énergie', 'Focus'],
    variants: [
      { label: '1g', pricePerUnit: 8.99, totalPrice: 8.99, inStock: true },
      { label: '3g', pricePerUnit: 7.33, totalPrice: 21.99, discount: 18, inStock: true },
      { label: '5g', pricePerUnit: 6.60, totalPrice: 32.99, discount: 27, inStock: true },
    ],
    images: [img(3930, 'yakuza-sour')],
    molecule: 'HEC-10',
    moleculeColor: '#06b6d4',
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 42,
    isHigh: true,
  },

  // ═══════════════════════════════════════
  // PUFFS & VAPES
  // ═══════════════════════════════════════
  {
    id: '3710',
    slug: 'puff-kiwi-hec10',
    name: 'Puff Kiwi HEC-10',
    category: 'puff-vape',
    legalStatus: 'grey-zone',
    legalNote: 'HEC-10 — molécule en zone grise légale',
    warningNote: 'Produit psychoactif — usage responsable recommandé',
    smokellierQuote: 'Kiwi acidulé et hit instantané. La puff qui pique.',
    tasteScore: 8.8,
    effectScore: 8.5,
    description: 'Puff jetable au kiwi infusée HEC-10. Saveur acidulée et fruitée, effets rapides. Environ 600 bouffées par puff.',
    aromas: ['Kiwi', 'Acidulé', 'Fruité', 'Frais'],
    effects: ['Rapide', 'Euphorie', 'Discret'],
    variants: [
      { label: '1 puff', pricePerUnit: 19.99, totalPrice: 19.99, inStock: true },
      { label: '3 puffs', pricePerUnit: 16.66, totalPrice: 49.99, discount: 17, inStock: true },
    ],
    images: [img(3710, 'puff-kiwi-hec10')],
    molecule: 'HEC-10',
    moleculeColor: '#06b6d4',
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 60,
    isHigh: true,
  },
  {
    id: '3712',
    slug: 'puff-lemon-hec10',
    name: 'Puff Lemon HEC-10',
    category: 'puff-vape',
    legalStatus: 'grey-zone',
    legalNote: 'HEC-10 — molécule en zone grise légale',
    warningNote: 'Produit psychoactif — usage responsable recommandé',
    smokellierQuote: 'Citron frais et bouffée puissante. Le réveil acidulé.',
    tasteScore: 8.6,
    effectScore: 8.5,
    description: 'Puff jetable au citron infusée HEC-10. Saveur citronnée intense et rafraîchissante. Environ 600 bouffées.',
    aromas: ['Citron', 'Agrumes', 'Frais', 'Acidulé'],
    effects: ['Rapide', 'Énergie', 'Discret'],
    variants: [
      { label: '1 puff', pricePerUnit: 19.99, totalPrice: 19.99, inStock: true },
      { label: '3 puffs', pricePerUnit: 16.66, totalPrice: 49.99, discount: 17, inStock: true },
    ],
    images: [img(3712, 'puff-lemon-hec10')],
    molecule: 'HEC-10',
    moleculeColor: '#06b6d4',
    isNew: false,
    isBestSeller: true,
    isOnSale: false,
    stock: 55,
    isHigh: true,
  },
  {
    id: '4720',
    slug: 'puff-mango-hec10',
    name: 'Puff Mango HEC-10',
    category: 'puff-vape',
    legalStatus: 'grey-zone',
    legalNote: 'HEC-10 — molécule en zone grise légale',
    warningNote: 'Produit psychoactif — usage responsable recommandé',
    smokellierQuote: 'Mangue tropicale et buzz instantané. Paradis en bouffée.',
    tasteScore: 9.0,
    effectScore: 8.5,
    description: 'Puff jetable à la mangue infusée HEC-10. Saveur tropicale exotique et sucrée. Environ 600 bouffées.',
    aromas: ['Mangue', 'Tropical', 'Sucré', 'Exotique'],
    effects: ['Rapide', 'Euphorie', 'Relaxation'],
    variants: [
      { label: '1 puff', pricePerUnit: 19.99, totalPrice: 19.99, inStock: true },
      { label: '3 puffs', pricePerUnit: 16.66, totalPrice: 49.99, discount: 17, inStock: true },
    ],
    images: [img(4720, 'puff-mango-hec10')],
    molecule: 'HEC-10',
    moleculeColor: '#06b6d4',
    isNew: true,
    isBestSeller: false,
    isOnSale: false,
    stock: 50,
    isHigh: true,
  },
  {
    id: '3495',
    slug: 'puff-crazy-dog',
    name: 'Puff Crazy Dog',
    category: 'puff-vape',
    legalStatus: 'grey-zone',
    legalNote: 'Magic Sauce — molécule en zone grise',
    warningNote: 'Produit très puissant — usage responsable',
    smokellierQuote: 'Le chien fou en version puff. Explosif.',
    tasteScore: 8.5,
    effectScore: 9.2,
    description: 'Puff jetable Crazy Dog infusée Magic Sauce. La puissance de la Magic Sauce dans un format discret et portable. Environ 600 bouffées.',
    aromas: ['Fruité', 'Sucré', 'Exotique', 'Intense'],
    effects: ['Très puissant', 'Euphorie', 'Stone'],
    variants: [
      { label: '1 puff', pricePerUnit: 24.99, totalPrice: 24.99, inStock: true },
      { label: '3 puffs', pricePerUnit: 21.66, totalPrice: 64.99, discount: 13, inStock: true },
    ],
    images: [img(3495, 'puff-crazy-dog')],
    molecule: 'Magic Sauce',
    moleculeColor: '#ec4899',
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 35,
    isHigh: true,
  },

  // ═══════════════════════════════════════
  // MAGIC SAUCE
  // ═══════════════════════════════════════
  {
    id: '3490',
    slug: 'crazy-dog-magic-sauce',
    name: 'Crazy Dog Magic Sauce',
    category: 'magic-sauce',
    legalStatus: 'grey-zone',
    legalNote: 'Magic Sauce — molécule en zone grise',
    warningNote: 'Produit TRÈS puissant — réservé aux utilisateurs expérimentés',
    smokellierQuote: 'Le chien fou. Brutal, explosif, mémorable. Pas pour les timides.',
    tasteScore: 8.3,
    effectScore: 9.8,
    description: 'Le Crazy Dog Magic Sauce est le produit le plus puissant du catalogue. Fleur infusée avec la formule Magic Sauce exclusive. Effets extrêmement intenses et durables.',
    aromas: ['Intense', 'Chimique', 'Fruité', 'Sucré'],
    effects: ['Extrêmement puissant', 'Hallucinogène', 'Long lasting'],
    variants: [
      { label: '1g', pricePerUnit: 12.99, totalPrice: 12.99, inStock: true },
      { label: '3g', pricePerUnit: 10.00, totalPrice: 29.99, discount: 23, inStock: true },
      { label: '5g', pricePerUnit: 8.60, totalPrice: 42.99, discount: 34, inStock: true },
    ],
    images: [img(3490, 'crazy-dog-magic-sauce')],
    molecule: 'Magic Sauce',
    moleculeColor: '#ec4899',
    isNew: false,
    isBestSeller: true,
    isOnSale: false,
    stock: 40,
    isHigh: true,
  },
  {
    id: '3770',
    slug: 'destock-magic-sauce',
    name: 'Déstock Magic Sauce',
    category: 'magic-sauce',
    legalStatus: 'grey-zone',
    legalNote: 'Magic Sauce — molécule en zone grise',
    warningNote: 'Produit puissant — réservé aux utilisateurs expérimentés',
    smokellierQuote: 'La Magic Sauce à prix cassé. Même puissance, petit prix.',
    tasteScore: 7.5,
    effectScore: 9.0,
    description: 'Déstockage Magic Sauce — mêmes effets, packaging simplifié. Idéal pour découvrir la Magic Sauce sans se ruiner. Qualité identique, prix réduit.',
    aromas: ['Fruité', 'Terreux', 'Intense'],
    effects: ['Très puissant', 'Euphorie', 'Relaxation intense'],
    variants: [
      { label: '3g', pricePerUnit: 6.66, totalPrice: 19.99, inStock: true },
      { label: '5g', pricePerUnit: 5.80, totalPrice: 28.99, discount: 13, inStock: true },
      { label: '10g', pricePerUnit: 5.00, totalPrice: 49.99, discount: 25, inStock: true },
    ],
    images: [img(3770, 'destock-magic-sauce')],
    molecule: 'Magic Sauce',
    moleculeColor: '#ec4899',
    isNew: false,
    isBestSeller: false,
    isOnSale: true,
    discountPct: 30,
    stock: 65,
    isHigh: true,
  },
  {
    id: '4800',
    slug: 'this-is-sparta',
    name: 'This Is Sparta',
    category: 'magic-sauce',
    legalStatus: 'grey-zone',
    legalNote: 'Magic Sauce — molécule en zone grise',
    warningNote: 'Produit TRÈS puissant — réservé aux utilisateurs expérimentés',
    smokellierQuote: 'Spartiate. Pas de pitié, pas de compromis. La légende.',
    tasteScore: 8.5,
    effectScore: 9.7,
    description: 'This Is Sparta est une fleur Magic Sauce au profil guerrier. Arômes intenses, effets dévastateurs. Quand la puissance rencontre la qualité.',
    aromas: ['Épicé', 'Boisé', 'Intense', 'Terreux'],
    effects: ['Dévastateur', 'Stone profond', 'Euphorie'],
    variants: [
      { label: '1g', pricePerUnit: 12.99, totalPrice: 12.99, inStock: true },
      { label: '3g', pricePerUnit: 10.00, totalPrice: 29.99, discount: 23, inStock: true },
      { label: '5g', pricePerUnit: 8.60, totalPrice: 42.99, discount: 34, inStock: true },
    ],
    images: [img(4800, 'this-is-sparta')],
    molecule: 'Magic Sauce',
    moleculeColor: '#ec4899',
    isNew: true,
    isBestSeller: false,
    isOnSale: false,
    stock: 30,
    isHigh: true,
  },
  {
    id: '4802',
    slug: 'john-lemon',
    name: 'John Lemon',
    category: 'magic-sauce',
    legalStatus: 'grey-zone',
    legalNote: 'Magic Sauce — molécule en zone grise',
    warningNote: 'Produit puissant — réservé aux utilisateurs expérimentés',
    smokellierQuote: 'Imagine... un citron qui te met K.O. All you need is lemon.',
    tasteScore: 9.0,
    effectScore: 9.3,
    description: 'John Lemon est une fleur Magic Sauce au profil citronné explosif. L\'acidité du citron mariée à la puissance de la Magic Sauce. Un hit créatif et dévastateur.',
    aromas: ['Citron', 'Lemon', 'Acidulé', 'Frais'],
    effects: ['Créativité', 'Euphorie intense', 'Stone'],
    variants: [
      { label: '1g', pricePerUnit: 12.99, totalPrice: 12.99, inStock: true },
      { label: '3g', pricePerUnit: 10.00, totalPrice: 29.99, discount: 23, inStock: true },
      { label: '5g', pricePerUnit: 8.60, totalPrice: 42.99, discount: 34, inStock: true },
    ],
    images: [img(4802, 'john-lemon')],
    molecule: 'Magic Sauce',
    moleculeColor: '#ec4899',
    isNew: true,
    isBestSeller: false,
    isOnSale: false,
    stock: 28,
    isHigh: true,
  },
  {
    id: '4804',
    slug: 'hash-fresh-frozen',
    name: 'Hash Fresh Frozen',
    category: 'magic-sauce',
    legalStatus: 'grey-zone',
    legalNote: 'Magic Sauce — molécule en zone grise',
    warningNote: 'Produit très puissant — usage responsable',
    smokellierQuote: 'Fraîcheur cryogénique et puissance Magic Sauce. Le futur du hash.',
    tasteScore: 9.2,
    effectScore: 9.5,
    description: 'Le Hash Fresh Frozen est une résine Magic Sauce extraite à partir de matière fraîche congelée. Conservation maximale des terpènes. Le nec plus ultra de la résine infusée.',
    aromas: ['Frais', 'Terpénique', 'Fruité', 'Floral'],
    effects: ['Puissant', 'Terpènes vifs', 'Relaxation'],
    variants: [
      { label: '1g', pricePerUnit: 14.99, totalPrice: 14.99, inStock: true },
      { label: '3g', pricePerUnit: 11.66, totalPrice: 34.99, discount: 22, inStock: true },
      { label: '5g', pricePerUnit: 10.00, totalPrice: 49.99, discount: 33, inStock: true },
    ],
    images: [img(4804, 'hash-fresh-frozen')],
    molecule: 'Magic Sauce',
    moleculeColor: '#ec4899',
    isNew: true,
    isBestSeller: false,
    isOnSale: false,
    stock: 22,
    isHigh: true,
  },
  {
    id: '3492',
    slug: 'la-confidential',
    name: 'LA Confidential',
    category: 'magic-sauce',
    legalStatus: 'grey-zone',
    legalNote: 'Magic Sauce — molécule en zone grise',
    warningNote: 'Produit puissant — réservé aux utilisateurs expérimentés',
    smokellierQuote: 'Los Angeles underground. Confidentiel, exclusif, dévastateur.',
    tasteScore: 8.7,
    effectScore: 9.4,
    description: 'LA Confidential est une fleur Magic Sauce au profil kush californien. Arômes de pin et de diesel, effets profonds et durables. Un classique revisité en mode extrême.',
    aromas: ['Pin', 'Diesel', 'Kush', 'Terreux'],
    effects: ['Stone profond', 'Relaxation extrême', 'Anti-douleur'],
    variants: [
      { label: '1g', pricePerUnit: 12.99, totalPrice: 12.99, inStock: true },
      { label: '3g', pricePerUnit: 10.00, totalPrice: 29.99, discount: 23, inStock: true },
      { label: '5g', pricePerUnit: 8.60, totalPrice: 42.99, discount: 34, inStock: true },
    ],
    images: [img(3492, 'la-confidential')],
    molecule: 'Magic Sauce',
    moleculeColor: '#ec4899',
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 38,
    isHigh: true,
  },

  // ═══════════════════════════════════════
  // 10-OH-HHC
  // ═══════════════════════════════════════
  {
    id: '3534',
    slug: 'casper-10oh',
    name: 'Casper 10-OH',
    category: '10-oh-hhc',
    legalStatus: 'grey-zone',
    legalNote: '10-OH-HHC — molécule en zone grise légale',
    warningNote: 'Effets psychoactifs — commencer par de petites doses',
    smokellierQuote: 'Fantomatique, planant, unique. Casper te fait léviter.',
    tasteScore: 8.2,
    effectScore: 8.8,
    description: 'Casper 10-OH est une fleur infusée au 10-OH-HHC, un dérivé du HHC aux effets plus doux mais prolongés. Profil discret et effets progressifs.',
    aromas: ['Floral', 'Herbal', 'Léger', 'Frais'],
    effects: ['Planant', 'Progressif', 'Relaxation'],
    variants: [
      { label: '1g', pricePerUnit: 9.99, totalPrice: 9.99, inStock: true },
      { label: '3g', pricePerUnit: 8.00, totalPrice: 23.99, discount: 20, inStock: true },
      { label: '5g', pricePerUnit: 7.00, totalPrice: 34.99, discount: 30, inStock: true },
    ],
    images: [img(3534, 'casper-10oh')],
    molecule: '10-OH-HHC',
    moleculeColor: '#14b8a6',
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 48,
    isHigh: true,
  },
  {
    id: '3771',
    slug: 'destock-10oh',
    name: 'Déstock 10-OH',
    category: '10-oh-hhc',
    legalStatus: 'grey-zone',
    legalNote: '10-OH-HHC — molécule en zone grise légale',
    warningNote: 'Effets psychoactifs — commencer par de petites doses',
    smokellierQuote: 'Le 10-OH à prix mini. Même trip, petit budget.',
    tasteScore: 7.2,
    effectScore: 8.5,
    description: 'Déstockage 10-OH-HHC — qualité identique, packaging simplifié. Découvrez le 10-OH-HHC à prix réduit. Effets planants et progressifs garantis.',
    aromas: ['Terreux', 'Herbal', 'Neutre'],
    effects: ['Planant', 'Relaxation', 'Doux'],
    variants: [
      { label: '3g', pricePerUnit: 5.66, totalPrice: 16.99, inStock: true },
      { label: '5g', pricePerUnit: 5.00, totalPrice: 24.99, discount: 12, inStock: true },
      { label: '10g', pricePerUnit: 4.00, totalPrice: 39.99, discount: 29, inStock: true },
    ],
    images: [img(3771, 'destock-10oh')],
    molecule: '10-OH-HHC',
    moleculeColor: '#14b8a6',
    isNew: false,
    isBestSeller: false,
    isOnSale: true,
    discountPct: 25,
    stock: 70,
    isHigh: true,
  },

  // ═══════════════════════════════════════
  // THCA
  // ═══════════════════════════════════════
  {
    id: '4500',
    slug: 'box-thca',
    name: 'Box THCA',
    category: 'thca',
    legalStatus: 'grey-zone',
    legalNote: 'THCA — molécule en zone grise légale',
    warningNote: 'Le THCA se convertit en THC à la chaleur — effets psychoactifs',
    smokellierQuote: 'La box surprise THCA. Variétés rotatives, qualité constante.',
    tasteScore: 8.5,
    effectScore: 9.5,
    description: 'La Box THCA contient une sélection de fleurs riches en THCA. Le THCA se transforme en THC lors de la combustion. Box surprise avec variétés rotatives.',
    aromas: ['Variable', 'Premium', 'Intense'],
    effects: ['Très puissant', 'THC actif', 'Variable'],
    variants: [
      { label: '3.5g box', pricePerUnit: 11.43, totalPrice: 39.99, inStock: true },
      { label: '7g box', pricePerUnit: 9.99, totalPrice: 69.99, discount: 13, inStock: true },
    ],
    images: [img(4500, 'box-thca')],
    molecule: 'THCA',
    moleculeColor: '#f43f5e',
    isNew: true,
    isBestSeller: false,
    isOnSale: false,
    stock: 20,
    isHigh: true,
  },
  {
    id: '4502',
    slug: 'cartridge-thca',
    name: 'Cartridge THCA',
    category: 'thca',
    legalStatus: 'grey-zone',
    legalNote: 'THCA — molécule en zone grise légale',
    warningNote: 'Le THCA se convertit en THC à la chaleur — effets psychoactifs',
    smokellierQuote: 'Cartouche THCA premium. Vapeur pure, effets dévastateurs.',
    tasteScore: 8.8,
    effectScore: 9.6,
    description: 'Cartouche de vaporisation THCA. Distillat premium de THCA pour une vaporisation pure et puissante. Compatible batteries 510.',
    aromas: ['Terpènes naturels', 'Fruité', 'Pin'],
    effects: ['Dévastateur', 'Rapide', 'Intense'],
    variants: [
      { label: '0.5ml', pricePerUnit: 29.99, totalPrice: 29.99, inStock: false },
      { label: '1ml', pricePerUnit: 49.99, totalPrice: 49.99, inStock: false },
    ],
    images: [img(4502, 'cartridge-thca')],
    molecule: 'THCA',
    moleculeColor: '#f43f5e',
    isNew: true,
    isBestSeller: false,
    isOnSale: false,
    stock: 0,
    isHigh: true,
    isOutOfStock: true,
  },
  {
    id: '4504',
    slug: 'disposable-thca',
    name: 'Disposable THCA',
    category: 'thca',
    legalStatus: 'grey-zone',
    legalNote: 'THCA — molécule en zone grise légale',
    warningNote: 'Le THCA se convertit en THC à la chaleur — effets psychoactifs',
    smokellierQuote: 'Jetable THCA. Prêt à l\'emploi, puissance maximale.',
    tasteScore: 8.6,
    effectScore: 9.5,
    description: 'Vape jetable THCA prête à l\'emploi. Aucune configuration nécessaire. Distillat THCA premium avec terpènes naturels. Environ 800 bouffées.',
    aromas: ['Fruité', 'Terpènes', 'Sucré'],
    effects: ['Puissant', 'Pratique', 'Rapide'],
    variants: [
      { label: '1 puff', pricePerUnit: 34.99, totalPrice: 34.99, inStock: true },
      { label: '3 puffs', pricePerUnit: 30.00, totalPrice: 89.99, discount: 14, inStock: true },
    ],
    images: [img(4504, 'disposable-thca')],
    molecule: 'THCA',
    moleculeColor: '#f43f5e',
    isNew: true,
    isBestSeller: false,
    isOnSale: false,
    stock: 25,
    isHigh: true,
  },

  // ═══════════════════════════════════════
  // DELTA-9
  // ═══════════════════════════════════════
  {
    id: '3700',
    slug: 'gummies-delta9',
    name: 'Gummies Delta-9',
    category: 'delta-9',
    legalStatus: 'grey-zone',
    legalNote: 'Delta-9 THC < 0.3% par poids — zone grise légale',
    warningNote: 'Contient du Delta-9 THC — effets psychoactifs possibles',
    consumptionNote: 'Commencer par 1/2 gummy — attendre 1h30 avant de reprendre',
    smokellierQuote: 'Bonbons magiques. Doux à croquer, puissants à vivre.',
    tasteScore: 9.0,
    effectScore: 8.0,
    description: 'Gummies infusés au Delta-9 THC (conforme < 0.3% par poids total). Saveurs fruitées variées. Effets progressifs et durables. Dosage précis par gummy.',
    aromas: ['Fruité', 'Bonbon', 'Sucré', 'Multi-saveurs'],
    effects: ['Progressif', 'Euphorie', 'Relaxation', 'Durable'],
    variants: [
      { label: '5 gummies', pricePerUnit: 3.00, totalPrice: 14.99, inStock: true },
      { label: '10 gummies', pricePerUnit: 2.50, totalPrice: 24.99, discount: 17, inStock: true },
      { label: '20 gummies', pricePerUnit: 2.00, totalPrice: 39.99, discount: 33, inStock: true },
    ],
    images: [img(3700, 'gummies-delta9')],
    molecule: 'Delta-9 THC',
    moleculeColor: '#eab308',
    isNew: false,
    isBestSeller: true,
    isOnSale: false,
    stock: 100,
    isHigh: true,
  },

  // ═══════════════════════════════════════
  // COOKIES
  // ═══════════════════════════════════════
  {
    id: '3650',
    slug: 'cookies-infused-gelato',
    name: 'Cookies Infused Gelato',
    category: 'cookies',
    legalStatus: 'grey-zone',
    legalNote: 'Produit infusé — molécule en zone grise',
    warningNote: 'Comestible infusé — effets retardés (1-2h)',
    consumptionNote: 'Manger 1/4 de cookie — attendre 2h avant de reprendre',
    smokellierQuote: 'Cookie gelato gourmand. Le dessert qui fait voyager.',
    tasteScore: 9.5,
    effectScore: 8.5,
    description: 'Cookies artisanaux infusés au profil Gelato. Pâte fondante, pépites de chocolat, et effets progressifs. Un délice gourmand avec des effets surprenants.',
    aromas: ['Chocolat', 'Vanille', 'Beurre', 'Gelato'],
    effects: ['Comestible', 'Progressif', 'Durable', 'Euphorie'],
    variants: [
      { label: '1 cookie', pricePerUnit: 9.99, totalPrice: 9.99, inStock: true },
      { label: '3 cookies', pricePerUnit: 8.33, totalPrice: 24.99, discount: 17, inStock: true },
      { label: '6 cookies', pricePerUnit: 7.50, totalPrice: 44.99, discount: 25, inStock: true },
    ],
    images: [img(3650, 'cookies-infused-gelato')],
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 45,
    isHigh: true,
  },

  // ═══════════════════════════════════════
  // ACCESSOIRES
  // ═══════════════════════════════════════
  {
    id: '3400',
    slug: 'kleaner-oral',
    name: 'Kleaner Oral',
    category: 'accessoires',
    legalStatus: 'legal',
    legalNote: 'Produit d\'hygiène — 100% légal',
    smokellierQuote: 'L\'allié discrétion. Spray oral post-session indispensable.',
    tasteScore: 5.0,
    effectScore: 0,
    description: 'Kleaner est un spray d\'hygiène buccale qui neutralise les traces salivaires. Format compact et discret. Utilisation simple et efficace.',
    aromas: ['Menthe', 'Frais'],
    effects: ['Hygiène', 'Discrétion'],
    variants: [
      { label: '1 spray', pricePerUnit: 14.99, totalPrice: 14.99, inStock: true },
      { label: '2 sprays', pricePerUnit: 12.50, totalPrice: 24.99, discount: 17, inStock: true },
    ],
    images: [img(3400, 'kleaner-oral')],
    isNew: false,
    isBestSeller: false,
    isOnSale: false,
    stock: 200,
  },
]

// ═══════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════

export const getBySlug = (slug: string): Product | undefined =>
  PRODUCTS.find((p) => p.slug === slug)

export const getBestsellers = (): Product[] =>
  PRODUCTS.filter((p) => p.isBestSeller && !p.isOutOfStock)

export const getNewArrivals = (): Product[] =>
  PRODUCTS.filter((p) => p.isNew && !p.isOutOfStock)

export const getOnSale = (): Product[] =>
  PRODUCTS.filter((p) => p.isOnSale && !p.isOutOfStock)

export const getRelated = (product: Product, limit = 4): Product[] =>
  PRODUCTS.filter(
    (p) =>
      p.id !== product.id &&
      p.category === product.category &&
      !p.isOutOfStock
  ).slice(0, limit)

export const getByCategory = (cat: Category): Product[] =>
  PRODUCTS.filter((p) => p.category === cat)
